version: "3"
services:

  gluster-server-1:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - "./gluster-server-1/etc/glusterfs:/etc/glusterfs:z"
      - "./gluster-server-1/var/lib/glusterd:/var/lib/glusterd:z"
      - "./gluster-server-1/var/log/glusterfs:/var/log/glusterfs:z"
    networks: 
      - "proxy"
    depends_on:
      - gluster-server-2
      - gluster-server-3
    command: sh -c "/usr/sbin/init" && gluster peer probe gluster-server-1 && gluster peer probe gluster-server-1

  gluster-server-2:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - "./gluster-server-2/etc/glusterfs:/etc/glusterfs:z"
      - "./gluster-server-2/var/lib/glusterd:/var/lib/glusterd:z"
      - "./gluster-server-2/var/log/glusterfs:/var/log/glusterfs:z"
    networks: 
      - "proxy"
    
  gluster-server-3:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - "./gluster-server-3/etc/glusterfs:/etc/glusterfs:z"
      - "./gluster-server-3/var/lib/glusterd:/var/lib/glusterd:z"
      - "./gluster-server-3/var/log/glusterfs:/var/log/glusterfs:z"
    networks: 
      - "proxy"

  app:
    build: ..
    ports:
      - "3000:3000"
    environment:
      - GLUSTERFS_SERVER_ADDR=gluster-server-1
    depends_on:
      - gluster-server-1

networks: 
  proxy:
    driver: bridge
