version: "3"
services:
  gluster-server-1:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - "./gluster-server-1/etc/glusterfs:/etc/glusterfs:z"
      - "./gluster-server-1/var/lib/glusterd:/var/lib/glusterd:z"
      - "./gluster-server-1/var/log/glusterfs:/var/log/glusterfs:z"
  gluster-server-2:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - "./gluster-server-2/etc/glusterfs:/etc/glusterfs:z"
      - "./gluster-server-2/var/lib/glusterd:/var/lib/glusterd:z"
      - "./gluster-server-2/var/log/glusterfs:/var/log/glusterfs:z"
    depends_on:
      - gluster-server-1
  app:
    build: ..
    ports:
      - "3000:3000"
    environment:
      - GLUSTERFS_SERVER_ADDR=gluster-server-1
    depends_on:
      - gluster-server-1
